<template>
  <div>
    <div>
      内容超出宽度范围显示tooltip：
      <y-tooltip-over
        content="您好您好您好您好您好您好您好您好您好您好"
        width="80px"
      />
    </div>
    <div>
      内容未超出宽度范围不显示tooltip：
      <y-tooltip-over
        content="您好您好您好您好您好您好您好您好您好您好"
        width="300px"
      />
    </div>
  </div>
</template>